apiVersion: skiperator.kartverket.no/v1alpha1
kind: Application
env:
  - name: M22_URL
    value: "TODO"
  - name: FRONTEND_URL
    value: "http://matrikkel-m22.atkv3-dev.kartverket-intern.cloud"
metadata:
  name: matrikkel-pdf-generering
  namespace: matrikkel-main
spec:
  image: "{{ image }}"
  port: 8086
  ingresses:
    - matrikkel-pdf-generering.atkv3-dev.kartverket-intern.cloud
  replicas: 1

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

  liveness:
    port: 8086
    path: /internal/isAlive
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
  readiness:
    port: 8086
    path: /internal/isReady
    initialDelay: 10      # default: 0
    failureThreshold: 6   # default: 3
